### ISSUE TITLE
Can't use angular-ra-newrelic with atomify/browserify + minifiy

### ISSUE THREAD

**Issue by ashleahhill** [red-ant/angular-ra-newrelic#1]
I am using angular-ra-newrelic within a project that uses [Atomify](https://github.com/atomify/atomify) to manage our dependencies. Because angular-ra-newrelic and angular-ra-pageload use implicit annotation instead of inline array notation for injected dependencies, minifying the code breaks the app.

Would it be possible to use inline array annotation so that the module can be bundled and minified?

**Comment by jsntv200** [comment]
v0.1.5 fixes ngAnnotate to add dependencies for the un-minified version
